name: Deploy Node.js Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-primary:
    runs-on: ubuntu-22.04

    steps:
      - name: Install SSH keys for Primary Server
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Connect to Primary Server, build image, and deploy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}

            # Write .env file from secret
            echo "${{ secrets.ENV_FILE }}" > .env

            # Pull latest changes from Git
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull

            # Build Docker image
            docker build -t playlightbackend .

            # Check if container playlightbackend exists
            if ! docker ps -a --format '{{.Names}}' | grep -q "^playlightbackend$"; then
              echo "Container playlightbackend does not exist, creating..."
              docker run -d -p 3009:3009 --network host --restart unless-stopped --name playlightbackend --env-file .env playlightbackend
            else
              echo "Container playlightbackend exists, stopping and removing..."
              docker stop playlightbackend || true
              docker rm playlightbackend || true
              docker run -d -p 3009:3009 --network host --restart unless-stopped --name playlightbackend --env-file .env playlightbackend
            fi
          EOF

      - name: Cleanup SSH for Primary Server
        run: rm -rf ~/.ssh